version: "3"
services:
    db:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - ./docker-db:/data/db
    api:
        image: hello-world-docker-express
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./:/usr/src/app
        depends_on: 
            - db
